// Dataset curado de craques reais das Copas do Mundo.
// Cada jogador: nome, país (ISO2 / subdivisão), Copa de referência, grupo de posição,
// detalhe legível e overall. Os grupos de posição são GK / DEF / MID / ATT.
//
// As fotos/nomes são apenas referência cultural; o jogo representa cada craque por um
// disco colorido + bandeira (sem uso de imagem real).

// ISO2 -> nome em português (apenas os países usados aqui).
export const COUNTRY = {
  AR: "Argentina", BE: "Bélgica", BG: "Bulgária", BR: "Brasil", CL: "Chile",
  CM: "Camarões", CO: "Colômbia", CR: "Costa Rica", CI: "Costa do Marfim",
  CZ: "Tchéquia", DE: "Alemanha", DK: "Dinamarca", EG: "Egito", ENG: "Inglaterra",
  ES: "Espanha", FR: "França", GH: "Gana", HR: "Croácia", IT: "Itália",
  KR: "Coreia do Sul", MA: "Marrocos", MX: "México", NG: "Nigéria", NL: "Holanda",
  PL: "Polônia", PT: "Portugal", PY: "Paraguai", RS: "Sérvia", RU: "Rússia",
  SCO: "Escócia", SN: "Senegal", UA: "Ucrânia", US: "Estados Unidos",
  UY: "Uruguai", WAL: "País de Gales",
};

// Bandeiras especiais (subdivisões do Reino Unido) que não têm ISO2 simples.
const SPECIAL_FLAG = {
  ENG: "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  SCO: "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  WAL: "🏴\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
};

// Converte um código de país em emoji de bandeira.
export function flagOf(code) {
  if (SPECIAL_FLAG[code]) return SPECIAL_FLAG[code];
  if (!code || code.length !== 2) return "🏳️";
  const A = 0x1f1e6;
  const up = code.toUpperCase();
  return String.fromCodePoint(A + (up.charCodeAt(0) - 65), A + (up.charCodeAt(1) - 65));
}

export function countryName(code) {
  return COUNTRY[code] || code;
}

// [nome, país, copa, grupo, detalhe, overall]
const RAW = [
  // ---------------- GOLEIROS ----------------
  ["Lev Yashin", "RU", 1958, "GK", "Goleiro", 90],
  ["Gordon Banks", "ENG", 1966, "GK", "Goleiro", 89],
  ["Dino Zoff", "IT", 1982, "GK", "Goleiro", 88],
  ["Peter Shilton", "ENG", 1986, "GK", "Goleiro", 85],
  ["Sepp Maier", "DE", 1974, "GK", "Goleiro", 86],
  ["Gilmar", "BR", 1958, "GK", "Goleiro", 85],
  ["Cláudio Taffarel", "BR", 1994, "GK", "Goleiro", 84],
  ["Oliver Kahn", "DE", 2002, "GK", "Goleiro", 89],
  ["Iker Casillas", "ES", 2010, "GK", "Goleiro", 90],
  ["Gianluigi Buffon", "IT", 2006, "GK", "Goleiro", 91],
  ["Manuel Neuer", "DE", 2014, "GK", "Goleiro", 91],
  ["Fabien Barthez", "FR", 1998, "GK", "Goleiro", 85],
  ["Petr Čech", "CZ", 2006, "GK", "Goleiro", 86],
  ["Hugo Lloris", "FR", 2018, "GK", "Goleiro", 86],
  ["Emiliano Martínez", "AR", 2022, "GK", "Goleiro", 86],
  ["Keylor Navas", "CR", 2014, "GK", "Goleiro", 84],
  ["Guillermo Ochoa", "MX", 2014, "GK", "Goleiro", 83],
  ["José Luis Chilavert", "PY", 1998, "GK", "Goleiro", 84],
  ["Thibaut Courtois", "BE", 2018, "GK", "Goleiro", 89],
  ["Edwin van der Sar", "NL", 1998, "GK", "Goleiro", 86],
  ["Peter Schmeichel", "DK", 1998, "GK", "Goleiro", 88],
  ["Ubaldo Fillol", "AR", 1978, "GK", "Goleiro", 85],
  ["Andoni Zubizarreta", "ES", 1994, "GK", "Goleiro", 84],
  ["Walter Zenga", "IT", 1990, "GK", "Goleiro", 84],
  ["Jorge Campos", "MX", 1994, "GK", "Goleiro", 82],
  ["Brad Friedel", "US", 2002, "GK", "Goleiro", 82],
  ["Tim Howard", "US", 2014, "GK", "Goleiro", 83],

  // ---------------- DEFENSORES ----------------
  ["Franz Beckenbauer", "DE", 1974, "DEF", "Líbero", 93],
  ["Paolo Maldini", "IT", 1994, "DEF", "Lateral", 92],
  ["Cafu", "BR", 2002, "DEF", "Lateral", 89],
  ["Roberto Carlos", "BR", 2002, "DEF", "Lateral", 89],
  ["Franco Baresi", "IT", 1994, "DEF", "Zagueiro", 90],
  ["Fabio Cannavaro", "IT", 2006, "DEF", "Zagueiro", 90],
  ["Carlos Alberto Torres", "BR", 1970, "DEF", "Lateral", 88],
  ["Daniel Passarella", "AR", 1978, "DEF", "Zagueiro", 87],
  ["Bobby Moore", "ENG", 1966, "DEF", "Zagueiro", 89],
  ["Lilian Thuram", "FR", 1998, "DEF", "Lateral", 87],
  ["Marcel Desailly", "FR", 1998, "DEF", "Zagueiro", 87],
  ["Laurent Blanc", "FR", 1998, "DEF", "Zagueiro", 85],
  ["Philipp Lahm", "DE", 2014, "DEF", "Lateral", 88],
  ["Jérôme Boateng", "DE", 2014, "DEF", "Zagueiro", 85],
  ["Mats Hummels", "DE", 2014, "DEF", "Zagueiro", 86],
  ["Sergio Ramos", "ES", 2010, "DEF", "Zagueiro", 89],
  ["Carles Puyol", "ES", 2010, "DEF", "Zagueiro", 87],
  ["Gerard Piqué", "ES", 2010, "DEF", "Zagueiro", 86],
  ["Giorgio Chiellini", "IT", 2006, "DEF", "Zagueiro", 86],
  ["Leonardo Bonucci", "IT", 2014, "DEF", "Zagueiro", 85],
  ["Thiago Silva", "BR", 2014, "DEF", "Zagueiro", 88],
  ["David Luiz", "BR", 2014, "DEF", "Zagueiro", 83],
  ["Dani Alves", "BR", 2014, "DEF", "Lateral", 85],
  ["Marcelo", "BR", 2014, "DEF", "Lateral", 85],
  ["Ashley Cole", "ENG", 2006, "DEF", "Lateral", 84],
  ["Rio Ferdinand", "ENG", 2006, "DEF", "Zagueiro", 86],
  ["John Terry", "ENG", 2006, "DEF", "Zagueiro", 85],
  ["Jaap Stam", "NL", 1998, "DEF", "Zagueiro", 86],
  ["Frank de Boer", "NL", 1998, "DEF", "Zagueiro", 84],
  ["Ronald Koeman", "NL", 1990, "DEF", "Zagueiro", 86],
  ["Andreas Brehme", "DE", 1990, "DEF", "Lateral", 85],
  ["Jürgen Kohler", "DE", 1990, "DEF", "Zagueiro", 84],
  ["Gaetano Scirea", "IT", 1982, "DEF", "Líbero", 86],
  ["Claudio Gentile", "IT", 1982, "DEF", "Zagueiro", 84],
  ["Júnior", "BR", 1982, "DEF", "Lateral", 85],
  ["Nílton Santos", "BR", 1958, "DEF", "Lateral", 86],
  ["Djalma Santos", "BR", 1958, "DEF", "Lateral", 85],
  ["Elías Figueroa", "CL", 1974, "DEF", "Zagueiro", 85],
  ["Ruud Krol", "NL", 1974, "DEF", "Zagueiro", 85],
  ["Berti Vogts", "DE", 1974, "DEF", "Lateral", 84],
  ["Antonio Cabrini", "IT", 1982, "DEF", "Lateral", 84],
  ["Oscar Ruggeri", "AR", 1986, "DEF", "Zagueiro", 84],
  ["José Luis Brown", "AR", 1986, "DEF", "Zagueiro", 82],
  ["Aldair", "BR", 1994, "DEF", "Zagueiro", 84],
  ["Jorginho", "BR", 1994, "DEF", "Lateral", 83],
  ["Fernando Hierro", "ES", 1994, "DEF", "Zagueiro", 86],
  ["Rafael Márquez", "MX", 2006, "DEF", "Zagueiro", 84],
  ["Iván Córdoba", "CO", 1998, "DEF", "Zagueiro", 82],
  ["Roberto Ayala", "AR", 2006, "DEF", "Zagueiro", 85],
  ["Walter Samuel", "AR", 2006, "DEF", "Zagueiro", 84],
  ["Javier Zanetti", "AR", 1998, "DEF", "Lateral", 86],
  ["Lúcio", "BR", 2002, "DEF", "Zagueiro", 85],
  ["Roque Júnior", "BR", 2002, "DEF", "Zagueiro", 81],
  ["Bixente Lizarazu", "FR", 1998, "DEF", "Lateral", 85],
  ["Willy Sagnol", "FR", 2006, "DEF", "Lateral", 83],
  ["Pepe", "PT", 2010, "DEF", "Zagueiro", 85],
  ["Ricardo Carvalho", "PT", 2006, "DEF", "Zagueiro", 85],
  ["Vincent Kompany", "BE", 2014, "DEF", "Zagueiro", 87],
  ["Jan Vertonghen", "BE", 2014, "DEF", "Zagueiro", 84],
  ["Toby Alderweireld", "BE", 2018, "DEF", "Zagueiro", 85],
  ["Virgil van Dijk", "NL", 2022, "DEF", "Zagueiro", 90],
  ["Raphaël Varane", "FR", 2018, "DEF", "Zagueiro", 87],
  ["Benjamin Pavard", "FR", 2018, "DEF", "Lateral", 82],
  ["Lucas Hernández", "FR", 2018, "DEF", "Lateral", 83],
  ["Aymeric Laporte", "ES", 2022, "DEF", "Zagueiro", 84],
  ["Achraf Hakimi", "MA", 2022, "DEF", "Lateral", 85],
  ["Theo Hernández", "FR", 2022, "DEF", "Lateral", 84],
  ["Joško Gvardiol", "HR", 2022, "DEF", "Zagueiro", 84],
  ["Kyle Walker", "ENG", 2022, "DEF", "Lateral", 84],
  ["Rúben Dias", "PT", 2022, "DEF", "Zagueiro", 86],
  ["Éder Militão", "BR", 2022, "DEF", "Zagueiro", 84],
  ["Nicolás Otamendi", "AR", 2022, "DEF", "Zagueiro", 83],
  ["Cristian Romero", "AR", 2022, "DEF", "Zagueiro", 84],
  ["Nahuel Molina", "AR", 2022, "DEF", "Lateral", 81],

  // ---------------- MEIO-CAMPISTAS ----------------
  ["Zinedine Zidane", "FR", 1998, "MID", "Meia", 95],
  ["Diego Maradona", "AR", 1986, "MID", "Meia", 95],
  ["Michel Platini", "FR", 1986, "MID", "Meia", 92],
  ["Lothar Matthäus", "DE", 1990, "MID", "Meia", 91],
  ["Andrés Iniesta", "ES", 2010, "MID", "Meia", 92],
  ["Xavi Hernández", "ES", 2010, "MID", "Meia", 91],
  ["Luka Modrić", "HR", 2018, "MID", "Meia", 91],
  ["Andrea Pirlo", "IT", 2006, "MID", "Volante", 90],
  ["Frank Rijkaard", "NL", 1990, "MID", "Volante", 88],
  ["Ruud Gullit", "NL", 1990, "MID", "Meia", 90],
  ["Rivelino", "BR", 1970, "MID", "Meia", 89],
  ["Gérson", "BR", 1970, "MID", "Meia", 87],
  ["Sócrates", "BR", 1982, "MID", "Meia", 90],
  ["Zico", "BR", 1982, "MID", "Meia", 91],
  ["Falcão", "BR", 1982, "MID", "Volante", 87],
  ["Toninho Cerezo", "BR", 1982, "MID", "Volante", 83],
  ["Dunga", "BR", 1994, "MID", "Volante", 84],
  ["Rivaldo", "BR", 2002, "MID", "Meia", 90],
  ["Ronaldinho", "BR", 2002, "MID", "Meia", 92],
  ["Kaká", "BR", 2006, "MID", "Meia", 90],
  ["Bobby Charlton", "ENG", 1966, "MID", "Meia", 91],
  ["Paul Gascoigne", "ENG", 1990, "MID", "Meia", 86],
  ["Steven Gerrard", "ENG", 2006, "MID", "Meia", 87],
  ["Frank Lampard", "ENG", 2006, "MID", "Meia", 86],
  ["Paul Scholes", "ENG", 2002, "MID", "Meia", 86],
  ["David Beckham", "ENG", 2002, "MID", "Meia", 86],
  ["Didi", "BR", 1958, "MID", "Meia", 88],
  ["Wolfgang Overath", "DE", 1970, "MID", "Meia", 85],
  ["Günter Netzer", "DE", 1974, "MID", "Meia", 85],
  ["Enzo Francescoli", "UY", 1986, "MID", "Meia", 87],
  ["Carlos Valderrama", "CO", 1990, "MID", "Meia", 86],
  ["Jay-Jay Okocha", "NG", 1998, "MID", "Meia", 84],
  ["Michael Laudrup", "DK", 1998, "MID", "Meia", 87],
  ["Pavel Nedvěd", "CZ", 2006, "MID", "Meia", 87],
  ["Luís Figo", "PT", 2006, "MID", "Ponta", 89],
  ["Deco", "PT", 2006, "MID", "Meia", 85],
  ["Rui Costa", "PT", 2002, "MID", "Meia", 85],
  ["Gilberto Silva", "BR", 2002, "MID", "Volante", 82],
  ["Emerson", "BR", 2002, "MID", "Volante", 83],
  ["Patrick Vieira", "FR", 1998, "MID", "Volante", 87],
  ["Didier Deschamps", "FR", 1998, "MID", "Volante", 84],
  ["Emmanuel Petit", "FR", 1998, "MID", "Volante", 83],
  ["Claude Makélélé", "FR", 2006, "MID", "Volante", 85],
  ["Yaya Touré", "CI", 2010, "MID", "Volante", 85],
  ["Michael Essien", "GH", 2006, "MID", "Volante", 84],
  ["Bastian Schweinsteiger", "DE", 2014, "MID", "Volante", 88],
  ["Toni Kroos", "DE", 2014, "MID", "Meia", 89],
  ["Mesut Özil", "DE", 2014, "MID", "Meia", 87],
  ["Sami Khedira", "DE", 2014, "MID", "Volante", 83],
  ["Sergio Busquets", "ES", 2010, "MID", "Volante", 87],
  ["Xabi Alonso", "ES", 2010, "MID", "Volante", 86],
  ["David Silva", "ES", 2010, "MID", "Meia", 88],
  ["Cesc Fàbregas", "ES", 2010, "MID", "Meia", 85],
  ["N'Golo Kanté", "FR", 2018, "MID", "Volante", 88],
  ["Paul Pogba", "FR", 2018, "MID", "Meia", 86],
  ["Blaise Matuidi", "FR", 2018, "MID", "Volante", 82],
  ["Arturo Vidal", "CL", 2014, "MID", "Volante", 85],
  ["Javier Mascherano", "AR", 2014, "MID", "Volante", 85],
  ["Esteban Cambiasso", "AR", 2006, "MID", "Volante", 83],
  ["Juan Román Riquelme", "AR", 2006, "MID", "Meia", 88],
  ["Wesley Sneijder", "NL", 2010, "MID", "Meia", 87],
  ["Rodri", "ES", 2022, "MID", "Volante", 88],
  ["Pedri", "ES", 2022, "MID", "Meia", 85],
  ["Gavi", "ES", 2022, "MID", "Meia", 82],
  ["Jude Bellingham", "ENG", 2022, "MID", "Meia", 86],
  ["Declan Rice", "ENG", 2022, "MID", "Volante", 83],
  ["Bruno Fernandes", "PT", 2022, "MID", "Meia", 86],
  ["Bernardo Silva", "PT", 2022, "MID", "Meia", 86],
  ["Kevin De Bruyne", "BE", 2018, "MID", "Meia", 91],
  ["Frenkie de Jong", "NL", 2022, "MID", "Meia", 85],
  ["Sergej Milinković-Savić", "RS", 2022, "MID", "Meia", 83],
  ["Enzo Fernández", "AR", 2022, "MID", "Meia", 84],
  ["Alexis Mac Allister", "AR", 2022, "MID", "Meia", 83],
  ["Rodrigo De Paul", "AR", 2022, "MID", "Volante", 83],
  ["Sofyan Amrabat", "MA", 2022, "MID", "Volante", 82],
  ["Casemiro", "BR", 2022, "MID", "Volante", 87],

  // ---------------- ATACANTES ----------------
  ["Pelé", "BR", 1970, "ATT", "Atacante", 95],
  ["Garrincha", "BR", 1962, "ATT", "Ponta", 92],
  ["Johan Cruyff", "NL", 1974, "ATT", "Atacante", 94],
  ["Ronaldo", "BR", 2002, "ATT", "Atacante", 95],
  ["Gerd Müller", "DE", 1974, "ATT", "Centroavante", 91],
  ["Eusébio", "PT", 1966, "ATT", "Atacante", 91],
  ["Just Fontaine", "FR", 1958, "ATT", "Atacante", 88],
  ["Romário", "BR", 1994, "ATT", "Atacante", 91],
  ["Gabriel Batistuta", "AR", 1998, "ATT", "Centroavante", 89],
  ["Marco van Basten", "NL", 1990, "ATT", "Centroavante", 91],
  ["Roberto Baggio", "IT", 1994, "ATT", "Atacante", 91],
  ["Paolo Rossi", "IT", 1982, "ATT", "Atacante", 88],
  ["Careca", "BR", 1986, "ATT", "Atacante", 86],
  ["Hristo Stoichkov", "BG", 1994, "ATT", "Atacante", 88],
  ["Davor Šuker", "HR", 1998, "ATT", "Atacante", 86],
  ["Gary Lineker", "ENG", 1986, "ATT", "Atacante", 86],
  ["Jürgen Klinsmann", "DE", 1990, "ATT", "Atacante", 87],
  ["Rudi Völler", "DE", 1990, "ATT", "Atacante", 85],
  ["Karl-Heinz Rummenigge", "DE", 1982, "ATT", "Atacante", 88],
  ["Mario Kempes", "AR", 1978, "ATT", "Atacante", 87],
  ["Diego Forlán", "UY", 2010, "ATT", "Atacante", 86],
  ["Luis Suárez", "UY", 2010, "ATT", "Atacante", 89],
  ["Edinson Cavani", "UY", 2018, "ATT", "Centroavante", 86],
  ["Thierry Henry", "FR", 2006, "ATT", "Atacante", 90],
  ["David Trezeguet", "FR", 2006, "ATT", "Atacante", 84],
  ["Raúl", "ES", 2002, "ATT", "Atacante", 87],
  ["Fernando Torres", "ES", 2010, "ATT", "Atacante", 86],
  ["David Villa", "ES", 2010, "ATT", "Atacante", 87],
  ["Samuel Eto'o", "CM", 2010, "ATT", "Atacante", 87],
  ["Didier Drogba", "CI", 2010, "ATT", "Centroavante", 88],
  ["Roger Milla", "CM", 1990, "ATT", "Atacante", 84],
  ["Hernán Crespo", "AR", 2002, "ATT", "Atacante", 85],
  ["Andriy Shevchenko", "UA", 2006, "ATT", "Atacante", 88],
  ["Wayne Rooney", "ENG", 2006, "ATT", "Atacante", 86],
  ["Michael Owen", "ENG", 2002, "ATT", "Atacante", 86],
  ["Alan Shearer", "ENG", 1998, "ATT", "Atacante", 86],
  ["Dennis Bergkamp", "NL", 1998, "ATT", "Atacante", 89],
  ["Patrick Kluivert", "NL", 1998, "ATT", "Atacante", 86],
  ["Ruud van Nistelrooy", "NL", 2006, "ATT", "Atacante", 86],
  ["Robin van Persie", "NL", 2014, "ATT", "Atacante", 87],
  ["Arjen Robben", "NL", 2014, "ATT", "Ponta", 89],
  ["Miroslav Klose", "DE", 2014, "ATT", "Centroavante", 87],
  ["Lukas Podolski", "DE", 2014, "ATT", "Atacante", 83],
  ["Thomas Müller", "DE", 2014, "ATT", "Atacante", 86],
  ["Lionel Messi", "AR", 2022, "ATT", "Atacante", 96],
  ["Cristiano Ronaldo", "PT", 2018, "ATT", "Atacante", 94],
  ["Neymar", "BR", 2018, "ATT", "Atacante", 90],
  ["Kylian Mbappé", "FR", 2018, "ATT", "Atacante", 92],
  ["Antoine Griezmann", "FR", 2018, "ATT", "Atacante", 88],
  ["Olivier Giroud", "FR", 2018, "ATT", "Centroavante", 84],
  ["Karim Benzema", "FR", 2014, "ATT", "Atacante", 89],
  ["Sergio Agüero", "AR", 2014, "ATT", "Atacante", 88],
  ["Gonzalo Higuaín", "AR", 2014, "ATT", "Atacante", 85],
  ["Ángel Di María", "AR", 2022, "ATT", "Ponta", 85],
  ["Julián Álvarez", "AR", 2022, "ATT", "Atacante", 83],
  ["Lautaro Martínez", "AR", 2022, "ATT", "Centroavante", 84],
  ["Harry Kane", "ENG", 2018, "ATT", "Centroavante", 89],
  ["Raheem Sterling", "ENG", 2018, "ATT", "Ponta", 84],
  ["Romelu Lukaku", "BE", 2018, "ATT", "Centroavante", 85],
  ["Eden Hazard", "BE", 2018, "ATT", "Ponta", 89],
  ["Robert Lewandowski", "PL", 2022, "ATT", "Centroavante", 91],
  ["Hakim Ziyech", "MA", 2022, "ATT", "Ponta", 83],
  ["Youssef En-Nesyri", "MA", 2022, "ATT", "Centroavante", 81],
  ["Vinícius Júnior", "BR", 2022, "ATT", "Ponta", 86],
  ["Richarlison", "BR", 2022, "ATT", "Atacante", 82],
  ["Bukayo Saka", "ENG", 2022, "ATT", "Ponta", 83],
  ["Cody Gakpo", "NL", 2022, "ATT", "Atacante", 83],
  ["Mohamed Salah", "EG", 2018, "ATT", "Ponta", 89],
  ["Sadio Mané", "SN", 2022, "ATT", "Ponta", 87],
  ["Son Heung-min", "KR", 2022, "ATT", "Atacante", 86],
];

// Lista final de jogadores reais, com id estável.
export const REAL_PLAYERS = RAW.map(([name, country, cup, pos, detail, ovr], i) => ({
  id: `r${i + 1}`,
  name,
  country,
  flag: flagOf(country),
  cup,
  pos,
  detail,
  ovr,
}));

// Anos de Copa presentes no dataset (para filtros).
export const CUPS = [...new Set(REAL_PLAYERS.map((p) => p.cup))].sort((a, b) => a - b);

// Países presentes (para filtros), ordenados por nome.
export const COUNTRIES = [...new Set(REAL_PLAYERS.map((p) => p.country))].sort((a, b) =>
  countryName(a).localeCompare(countryName(b))
);
